### ISSUE TITLE
Offer module uses removed functionality from kcas package

### ISSUE THREAD

**Issue by henrymercer** [ocaml-multicore/reagents#23]
Line 42 of `lib/offer.ml` references `Kcas.get_id ()`, however this function has been removed in commit https://github.com/kayceesrk/kcas/commit/d13586b62bb6d5ff91ebddf180b564a1edf395bc  to the kcas package.

https://github.com/ocamllabs/reagents/blob/69f5babbf731fd193d221fc437275d9d32b8a1d7/lib/offer.ml#L42

**Comment by bartoszmodelski** [comment]
I believe https://github.com/ocaml-multicore/kcas/commit/af0dcb8ed2a0d2eae12de3c76e8ba4ba18951435 fixes this.
